plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - evaluando_project_manager.md
  - entrevistando_software_engineers.md

theme: jekyll-theme-minimal 
